name: intera
description: "INTERA - Ask. Answer. Earn Karma."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Authentication
  google_sign_in: ^6.2.1

  # Permissions
  permission_handler: ^11.3.1

  # Firebase
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Media
  image_picker: ^1.1.2
  video_player: ^2.9.1
  image: ^4.9.1
  tflite_flutter: ^0.12.1
  video_thumbnail: ^0.5.6
  path_provider: ^2.1.6
  flutter_local_notifications: ^22.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/core/constants/assets/images/intera_app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/core/constants/assets/images/intera_app_icon.png
    - assets/models/