// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdSX7xYUCKwMlbk2X268fgswnJHa2Ye8',
    appId: '1:685777373489:web:16e63a9b4a8dd518720810',
    messagingSenderId: '685777373489',
    projectId: 'intera-1505',
    authDomain: 'intera-1505.firebaseapp.com',
    storageBucket: 'intera-1505.firebasestorage.app',
    measurementId: 'G-HS22W5S1KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXXVvf5dn2gRFfTojH0HE_HJs9VegbPds',
    appId: '1:685777373489:android:f1f6f366acfe2aae720810',
    messagingSenderId: '685777373489',
    projectId: 'intera-1505',
    storageBucket: 'intera-1505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDibAsjnK3USWkru_IhF8ByjQJiqJKcfQc',
    appId: '1:685777373489:ios:28411841ac6e1a17720810',
    messagingSenderId: '685777373489',
    projectId: 'intera-1505',
    storageBucket: 'intera-1505.firebasestorage.app',
    iosBundleId: 'com.example.intera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDibAsjnK3USWkru_IhF8ByjQJiqJKcfQc',
    appId: '1:685777373489:ios:28411841ac6e1a17720810',
    messagingSenderId: '685777373489',
    projectId: 'intera-1505',
    storageBucket: 'intera-1505.firebasestorage.app',
    iosBundleId: 'com.example.intera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKdSX7xYUCKwMlbk2X268fgswnJHa2Ye8',
    appId: '1:685777373489:web:7bf95def63e955cb720810',
    messagingSenderId: '685777373489',
    projectId: 'intera-1505',
    authDomain: 'intera-1505.firebaseapp.com',
    storageBucket: 'intera-1505.firebasestorage.app',
    measurementId: 'G-LXL6W7P4HL',
  );
}
